var testlocal = ["r"];
    localStorage.setItem('testlocal', JSON.stringify(testlocal));

    const ArrayListProducts = [
        {
            img: "./image/selling-products.webp",
            name: "Laptop LG Gram 2023 14Z90R GAH53A5",
            thuonghieu: "LG",
            phanloai: "gaming",
            cpu: "Intel Core i7",
            vga: "RTX 3070",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop ASUS Gram 2023 14Z90R GAH53A5",
            thuonghieu: "ASUS",
            phanloai: "oldgaming",
            cpu: "Intel Core i7",
            vga: "RTX 3070",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "5490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop DELL Gram 2023 14Z90R GAH53A5",
            thuonghieu: "DELL",
            phanloai: "vanphong",
            cpu: "Intel Core i5",
            vga: "RTX 3050",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop HP Gram 2023 14Z90R GAH53A5",
            thuonghieu: "HP",
            phanloai: "vanphong",
            cpu: "Intel Core i5",
            vga: "RTX 3060",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop APPLE Gram 2023 14Z90R GAH53A5",
            thuonghieu: "APPLE",
            phanloai: "doanhnhan",
            cpu: "Xeon",
            vga: "RTX 3070",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop VIVOZENBOOK Gram 2023 14Z90R GAH53A5",
            thuonghieu: "VIVOZENBOOK",
            phanloai: "dohoa",
            cpu: "Intel Core i7",
            vga: "RTX 3070 Ti",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop GIGABYTE Gram 2023 14Z90R GAH53A5",
            thuonghieu: "GIGABYTE",
            phanloai: "dohoa",
            cpu: "Intel Core i5",
            vga: "RTX 3060",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "5490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop LG Gram 2022 ",
            thuonghieu: "LG",
            phanloai: "gaming",
            cpu: "Intel Core i5",
            vga: "RTX 3050",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop ACER Gram 2023 14Z90R GAH53A5",
            thuonghieu: "ACER",
            phanloai: "gaming",
            cpu: "Intel Core i9",
            vga: "RTX 4060",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop ASUS TUF DASH Gram 2023 14Z90R GAH53A5",
            thuonghieu: "ASUS",
            phanloai: "gaming",
            cpu: "Intel Core i9",
            vga: "RTX 4080",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop LG Gram 2023 14Z90R GAH53A5",
            thuonghieu: "LG",
            phanloai: "dohoa",
            cpu: "Intel Core i5",
            vga: "RTX 3070 Ti",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "2490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop LG Gram 2023 14Z90R GAH53A5",
            thuonghieu: "LG",
            phanloai: "dohoa",
            cpu: "ADM Ryzen 5",
            vga: "RTX 3080",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "9490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop ASUS Gram 2023 14Z90R GAH53A5",
            thuonghieu: "ASUS",
            phanloai: "gaming",
            cpu: "Intel Core i7",
            vga: "RTX 3080",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "35490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop DELL Gram 2023 14Z90R GAH53A5",
            thuonghieu: "DELL",
            phanloai: "vanphong",
            cpu: "ADM Ryzen 5",
            vga: "RTX 3050 Ti",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "15490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop HP Gram 2023 14Z90R GAH53A5",
            thuonghieu: "HP",
            phanloai: "vanphong",
            cpu: "ADM Ryzen 7",
            vga: "RTX 3070 Ti",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "45490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop APPLE Gram 2023 14Z90R GAH53A5",
            thuonghieu: "APPLE",
            phanloai: "doanhnhan",
            cpu: "Xeon",
            vga: "RTX 3070",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "17490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop LG Gram 2023 14Z90R GAH53A5",
            thuonghieu: "LG",
            phanloai: "dohoa",
            cpu: "Intel Core i7",
            vga: "RTX 3070",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop ASUS Gram 2023 14Z90R GAH53A5",
            thuonghieu: "ASUS",
            phanloai: "gaming",
            cpu: "Intel Core i7",
            vga: "RTX 3070",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "5490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop DELL Gram 2023 14Z90R GAH53A5",
            thuonghieu: "DELL",
            phanloai: "vanphong",
            cpu: "Intel Core i5",
            vga: "RTX 3050",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop HP Gram 2023 14Z90R GAH53A5",
            thuonghieu: "HP",
            phanloai: "vanphong",
            cpu: "Intel Core i5",
            vga: "RTX 3060",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop APPLE Gram 2023 14Z90R GAH53A5",
            thuonghieu: "APPLE",
            phanloai: "doanhnhan",
            cpu: "Xeon",
            vga: "RTX 3070",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop VIVOZENBOOK Gram 2023 14Z90R GAH53A5",
            thuonghieu: "VIVOZENBOOK",
            phanloai: "dohoa",
            cpu: "Intel Core i7",
            vga: "RTX 3070 Ti",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop LG Gram 2023 14Z90R GAH53A5",
            thuonghieu: "LG",
            phanloai: "dohoa",
            cpu: "Intel Core i7",
            vga: "RTX 3070",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop ASUS Gram 2023 14Z90R GAH53A5",
            thuonghieu: "ASUS",
            phanloai: "gaming",
            cpu: "Intel Core i7",
            vga: "RTX 3070",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "5490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop DELL Gram 2023 14Z90R GAH53A5",
            thuonghieu: "DELL",
            phanloai: "vanphong",
            cpu: "Intel Core i5",
            vga: "RTX 3050",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop HP Gram 2023 14Z90R GAH53A5",
            thuonghieu: "HP",
            phanloai: "vanphong",
            cpu: "Intel Core i5",
            vga: "RTX 3060",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop APPLE Gram 2023 14Z90R GAH53A5",
            thuonghieu: "APPLE",
            phanloai: "doanhnhan",
            cpu: "Xeon",
            vga: "RTX 3070",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop VIVOZENBOOK Gram 2023 14Z90R GAH53A5",
            thuonghieu: "VIVOZENBOOK",
            phanloai: "dohoa",
            cpu: "Intel Core i7",
            vga: "RTX 3070 Ti",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop GIGABYTE Gram 2023 14Z90R GAH53A5",
            thuonghieu: "GIGABYTE",
            phanloai: "other",
            cpu: "Intel Core i5",
            vga: "RTX 3060",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "5490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop LG Gram 2022 ",
            thuonghieu: "LG",
            phanloai: "other",
            cpu: "Intel Core i5",
            vga: "RTX 3050",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop ACER Gram 2023 14Z90R GAH53A5",
            thuonghieu: "ACER",
            phanloai: "new99",
            cpu: "Intel Core i9",
            vga: "RTX 4060",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop ASUS TUF DASH Gram 2023 14Z90R GAH53A5",
            thuonghieu: "ASUS",
            phanloai: "oldgaming",
            cpu: "Intel Core i9",
            vga: "RTX 4080",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop LG Gram 2023 14Z90R GAH53A5",
            thuonghieu: "LG",
            phanloai: "oldvanphong",
            cpu: "Intel Core i5",
            vga: "RTX 3070 Ti",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "2490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop LG Gram 2023 14Z90R GAH53A5",
            thuonghieu: "LG",
            phanloai: "new99",
            cpu: "ADM Ryzen 5",
            vga: "RTX 3080",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "9490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop GIGABYTE Gram 2023 14Z90R GAH53A5",
            thuonghieu: "GIGABYTE",
            phanloai: "oldgaming",
            cpu: "Intel Core i5",
            vga: "RTX 3060",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "5490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop LG Gram 2022 ",
            thuonghieu: "LG",
            phanloai: "oldgaming",
            cpu: "Intel Core i5",
            vga: "RTX 3050",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop ACER Gram 2023 14Z90R GAH53A5",
            thuonghieu: "ACER",
            phanloai: "oldgaming",
            cpu: "Intel Core i9",
            vga: "RTX 4060",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop ASUS TUF DASH Gram 2023 14Z90R GAH53A5",
            thuonghieu: "ASUS",
            phanloai: "oldgaming",
            cpu: "Intel Core i9",
            vga: "RTX 4080",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "25490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop LG Gram 2023 14Z90R GAH53A5",
            thuonghieu: "LG",
            phanloai: "oldvanphong",
            cpu: "Intel Core i5",
            vga: "RTX 3070 Ti",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "2490000",
            labelonsale: "-21%"
        },
        {
            img: "./image/selling-products.webp",
            name: "Laptop LG Gram 2023 14Z90R GAH53A5",
            thuonghieu: "LG",
            phanloai: "new99",
            cpu: "ADM Ryzen 5",
            vga: "RTX 3080",
            ram: "16 GB",
            ssd: "256 GB",
            lcd: "14 inch FHD+ IPS",
            pricecompare: "32.490.000₫",
            pricehighlight: "9490000",
            labelonsale: "-21%"
        }
    ];   

//Thêm mảng sản phẩm vào Local
localStorage.setItem('ArrayListProducts', JSON.stringify(ArrayListProducts));
// Lấy giá trị từ local storage
const storedJsonString = localStorage.getItem('ArrayListProducts');

// Chuyển đổi chuỗi JSON thành mảng
const storedArray = JSON.parse(storedJsonString);

// Sử dụng mảng trong file này
console.log(storedArray);
